### ISSUE TITLE
Start radius server using docker keeps restarting

### ISSUE THREAD

**Issue by Jeff-Tian** [vzakharchenko/keycloak-radius-plugin#542]
**Describe the bug**
Start radius server using docker keeps restarting

**To Reproduce**
1. Go to ['documentation'](https://github.com/vzakharchenko/keycloak-radius-plugin/blob/master/docker/README.md)
2. Run docker image following the doc `https://github.com/vzakharchenko/keycloak-radius-plugin/blob/master/docker/README.md`
3. Check log

```
~/keycloak-radius
⇡6% ➜ docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS                        PORTS     NAMES
f528760367f9   vassio/keycloak-radius-plugin   "/opt/radius/scripts…"   12 seconds ago   Restarting (0) 1 second ago             keycloak-radius-plugin

~/keycloak-radius
⇡6% ➜ docker logs f528
{"sharedSecret":"secret","authPort":1812,"accountPort":1813,"useUdpRadius":true,"externalDictionary":"""","radsec":{"privateKey":"/config/private.key","certificate":"/config/public.crt","useRadSec":false},"coa":{"port":3799,"useCoA":false}}
mkdir: created directory '/opt/keycloak/config/'
Keycloak - Open Source Identity and Access Management

Find more information at: https://www.keycloak.org/docs/latest

Usage:

kc.sh [OPTIONS] [COMMAND]

Use this command-line tool to manage your Keycloak cluster.
Make sure the command is available on your "PATH" or prefix it with "./" (e.g.:
"./kc.sh") to execute from the current folder.

Options:

-cf, --config-file <file>
                     Set the path to a configuration file. By default, configuration properties are
                       read from the "keycloak.conf" file in the "conf" directory.
-h, --help           This help message.
-v, --verbose        Print out error details when running this command.
-V, --version        Show version information

Commands:

  build                   Creates a new and optimized server image.
  start                   Start the server.
  start-dev               Start the server in development mode.
  export                  Export data from realms to a file or directory.
  import                  Import data from a directory or a file.
  show-config             Print out the current configuration.
  tools                   Utilities for use and interaction with the server.
    completion            Generate bash/zsh completion script for kc.sh.

Examples:

  Start the server in development mode for local development or testing:

      $ kc.sh start-dev

  Building an optimized server runtime:

      $ kc.sh build <OPTIONS>

  Start the server in production mode:

      $ kc.sh start <OPTIONS>

  Enable auto-completion to bash/zsh:

      $ source <(kc.sh tools completion)

  Please, take a look at the documentation for more details before deploying in
production.

Use "kc.sh start --help" for the available options when starting the server.
Use "kc.sh <command> --help" for more information about other commands.
{"sharedSecret":"secret","authPort":1812,"accountPort":1813,"useUdpRadius":true,"externalDictionary":"""","radsec":{"privateKey":"/config/private.key","certificate":"/config/public.crt","useRadSec":false},"coa":{"port":3799,"useCoA":false}}
Keycloak - Open Source Identity and Access Management

Find more information at: https://www.keycloak.org/docs/latest

Usage:

kc.sh [OPTIONS] [COMMAND]

Use this command-line tool to manage your Keycloak cluster.
Make sure the command is available on your "PATH" or prefix it with "./" (e.g.:
"./kc.sh") to execute from the current folder.

Options:

-cf, --config-file <file>
                     Set the path to a configuration file. By default, configuration properties are
                       read from the "keycloak.conf" file in the "conf" directory.
-h, --help           This help message.
-v, --verbose        Print out error details when running this command.
-V, --version        Show version information

Commands:

  build                   Creates a new and optimized server image.
  start                   Start the server.
  start-dev               Start the server in development mode.
  export                  Export data from realms to a file or directory.
  import                  Import data from a directory or a file.
  show-config             Print out the current configuration.
  tools                   Utilities for use and interaction with the server.
    completion            Generate bash/zsh completion script for kc.sh.

Examples:

  Start the server in development mode for local development or testing:

      $ kc.sh start-dev

  Building an optimized server runtime:

      $ kc.sh build <OPTIONS>

  Start the server in production mode:

      $ kc.sh start <OPTIONS>

  Enable auto-completion to bash/zsh:

      $ source <(kc.sh tools completion)

  Please, take a look at the documentation for more details before deploying in
production.

Use "kc.sh start --help" for the available options when starting the server.
Use "kc.sh <command> --help" for more information about other commands.
{"sharedSecret":"secret","authPort":1812,"accountPort":1813,"useUdpRadius":true,"externalDictionary":"""","radsec":{"privateKey":"/config/private.key","certificate":"/config/public.crt","useRadSec":false},"coa":{"port":3799,"useCoA":false}}
Keycloak - Open Source Identity and Access Management

Find more information at: https://www.keycloak.org/docs/latest

Usage:

kc.sh [OPTIONS] [COMMAND]

Use this command-line tool to manage your Keycloak cluster.
Make sure the command is available on your "PATH" or prefix it with "./" (e.g.:
"./kc.sh") to execute from the current folder.

Options:

-cf, --config-file <file>
                     Set the path to a configuration file. By default, configuration properties are
                       read from the "keycloak.conf" file in the "conf" directory.
-h, --help           This help message.
-v, --verbose        Print out error details when running this command.
-V, --version        Show version information

Commands:

  build                   Creates a new and optimized server image.
  start                   Start the server.
  start-dev               Start the server in development mode.
  export                  Export data from realms to a file or directory.
  import                  Import data from a directory or a file.
  show-config             Print out the current configuration.
  tools                   Utilities for use and interaction with the server.
    completion            Generate bash/zsh completion script for kc.sh.

Examples:

  Start the server in development mode for local development or testing:

      $ kc.sh start-dev

  Building an optimized server runtime:

      $ kc.sh build <OPTIONS>

  Start the server in production mode:

      $ kc.sh start <OPTIONS>

  Enable auto-completion to bash/zsh:

      $ source <(kc.sh tools completion)

  Please, take a look at the documentation for more details before deploying in
production.

Use "kc.sh start --help" for the available options when starting the server.
Use "kc.sh <command> --help" for more information about other commands.
```

**Expected behavior**
Should not restart

**Screenshots**
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/3367820/159603241-bf2620f1-49e5-477c-aad5-307a5d501783.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey

**Additional context**
Tried on PWD the same issue.

https://www.docker.com/play-with-docker/

**Comment by Jeff-Tian** [comment]
Checked the version 1.4.2, same issue. Checked 1.3.9, it works!

**Comment by Jeff-Tian** [comment]
1.3.9 also has issues:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/3367820/159604419-8caa6a2c-77f8-4d04-b3e7-ef95f078ab4d.png">

**Comment by maltegrosse** [comment]
try to add `start-dev` to your docker command. the providers need a `start build` command before running the container in production mode

**Comment by weltonrodrigo** [comment]
It seems the DockerFile is broken or the version 1.4.2 is intended to be run with arguments.

```terminal
$ docker run --rm -ti vassio/keycloak-radius-plugin:1.4.2

Radius Shared secret is empty.
Keycloak - Open Source Identity and Access Management

Find more information at: https://www.keycloak.org/docs/latest

Usage:

kc.sh [OPTIONS] [COMMAND]

Use this command-line tool to manage your Keycloak cluster.
Make sure the command is available on your "PATH" or prefix it with "./" (e.g.:
"./kc.sh") to execute from the current folder.

Options:

-cf, --config-file <file>
                     Set the path to a configuration file. By default, configuration properties are
                       read from the "keycloak.conf" file in the "conf" directory.
-h, --help           This help message.
-v, --verbose        Print out error details when running this command.
-V, --version        Show version information

Commands:

  build                   Creates a new and optimized server image.
  start                   Start the server.
  start-dev               Start the server in development mode.
  export                  Export data from realms to a file or directory.
  import                  Import data from a directory or a file.
  show-config             Print out the current configuration.
  tools                   Utilities for use and interaction with the server.
    completion            Generate bash/zsh completion script for kc.sh.

Examples:

  Start the server in development mode for local development or testing:

      $ kc.sh start-dev

  Building an optimized server runtime:

      $ kc.sh build <OPTIONS>

  Start the server in production mode:

      $ kc.sh start <OPTIONS>

  Enable auto-completion to bash/zsh:

      $ source <(kc.sh tools completion)

  Please, take a look at the documentation for more details before deploying in
production.

Use "kc.sh start --help" for the available options when starting the server.
Use "kc.sh <command> --help" for more information about other commands.
```

**Comment by maltegrosse** [comment]
as mentioned above, just add the start arguments. this is related to keycloak 17, not to this plugin

docker run --rm -ti vassio/keycloak-radius-plugin:1.4.2 **start-dev**

**Comment by maltegrosse** [comment]
as I struggled abit getting kc with postgres running, everything slightly changed from non legacy version **17.0.x**  onwards...

its worth following this howto: https://www.keycloak.org/server/containers if you want to use it in production...

In combination with the radius plugin, create a new Dockerfile e.g.

```
FROM vassio/keycloak-radius-plugin:latest as builder
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres
#RUN /opt/radius/scripts/docker-radius-entrypoint.sh build --db=postgres
RUN /opt/keycloak/bin/kc.sh build --db=postgres
FROM vassio/keycloak-radius-plugin:latest:1.4.2
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
EXPOSE 8080
EXPOSE 9990
EXPOSE 1812/udp
EXPOSE 1813/udp
ENTRYPOINT [ "/opt/radius/scripts/docker-radius-entrypoint.sh" ]
```

`docker build -t keycloak-custom:latest .`

now create e.g. a docker-compose.yml with following.... (this includes traefik as a reverse proxy)
it could be that not all parameters are correct:

```
services:
  keycloak:
    image: keycloak-custom:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminadmin
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: https://keycloak.example.com
      KEYCLOAK_HOSTNAME: keycloak.example.com
      KC_PROXY: edge
      KC_HOSTNAME: keycloak.example.com
      KC_HOSTNAME_STRICT_HTTPS: 'true'
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: whateverpw
      RADIUS_SHARED_SECRET: secret
      RADIUS_UDP: 'true'
      RADIUS_UDP_AUTH_PORT: 1812
      RADIUS_UDP_ACCOUNT_PORT: 1813
      RADIUS_RADSEC: 'false'
      RADIUS_DICTIONARY: ''
      RADIUS_RADSEC_PRIVATEKEY: /config/private.key
      RADIUS_RADSEC_CERTIFICATE: /config/public.crt
      RADIUS_COA: 'false'
      RADIUS_COA_PORT: 3799
      "keycloak.profile.feature.upload_scripts": enabled
    ports:
      - "8080:8080" #  UI
	# dont forget to route these ports to somewhere :)
      - "8190:8190" #  DEBUG
      - "1812:1812/udp" #  RADIUS
      - "1813:1813/udp" #  RADIUS
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kc.rule=Host(`keycloak.example.com`)"
      - "traefik.http.routers.kc.entrypoints=https"
      - "traefik.http.routers.kc.tls.certResolver=le"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.kc.priority=2"
      - "traefik.http.services.kc.loadbalancer.server.port=8080"
    depends_on:
      - postgres
    restart: always
    entrypoint: sh /opt/radius/scripts/docker-entrypoint.sh start --http-port=8080 --http-enabled=true --hostname-strict-https=true --hostname-strict=false
    networks:
      - web
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: keycloak
       POSTGRES_USER: keycloak
       POSTGRES_PASSWORD: whateverpw
    restart: always
    networks:
      - web

....
```

feedback welcome....

ps @vzakharchenko feel free to link to this comment in the docker readme file...
